//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TFEditor.Properties.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string ButtonOpenText {
            get {
                return ResourceManager.GetString("ButtonOpenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ButtonSaveText {
            get {
                return ResourceManager.GetString("ButtonSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Column1HeaderText {
            get {
                return ResourceManager.GetString("Column1HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line width.
        /// </summary>
        internal static string ColumnHeader8Text {
            get {
                return ResourceManager.GetString("ColumnHeader8Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width/Height.
        /// </summary>
        internal static string ColumnHeader9Text {
            get {
                return ResourceManager.GetString("ColumnHeader9Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save TYP file.
        /// </summary>
        internal static string FileDialogSaveTitleText {
            get {
                return ResourceManager.GetString("FileDialogSaveTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYP files (*.typ)|*.typ|All files|*.*.
        /// </summary>
        internal static string FileDialogTypFileFilterText {
            get {
                return ResourceManager.GetString("FileDialogTypFileFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FileMenuItemText {
            get {
                return ResourceManager.GetString("FileMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string HelpMenuText {
            get {
                return ResourceManager.GetString("HelpMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font color.
        /// </summary>
        internal static string LabelFontColorText {
            get {
                return ResourceManager.GetString("LabelFontColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string LabelFontText {
            get {
                return ResourceManager.GetString("LabelFontText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line width: ?.
        /// </summary>
        internal static string LabelLineWithText {
            get {
                return ResourceManager.GetString("LabelLineWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        internal static string LabelsNightText {
            get {
                return ResourceManager.GetString("LabelsNightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large image.
        /// </summary>
        internal static string LargeImageMenuItemText {
            get {
                return ResourceManager.GetString("LargeImageMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust text flow to line.
        /// </summary>
        internal static string LineTextRotationCheckBoxItemText {
            get {
                return ResourceManager.GetString("LineTextRotationCheckBoxItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin width.
        /// </summary>
        internal static string MarginWidthLabelText {
            get {
                return ResourceManager.GetString("MarginWidthLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Set color 1.
        /// </summary>
        internal static string MenuItemAreaColor1Text {
            get {
                return ResourceManager.GetString("MenuItemAreaColor1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Set color 2.
        /// </summary>
        internal static string MenuItemAreaColor2Text {
            get {
                return ResourceManager.GetString("MenuItemAreaColor2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Finish.
        /// </summary>
        internal static string MenuItemCloseText {
            get {
                return ResourceManager.GetString("MenuItemCloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy image.
        /// </summary>
        internal static string MenuItemCopyAreaText {
            get {
                return ResourceManager.GetString("MenuItemCopyAreaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change element &amp;TYP.
        /// </summary>
        internal static string MenuItemElementChangeTypText {
            get {
                return ResourceManager.GetString("MenuItemElementChangeTypText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy element.
        /// </summary>
        internal static string MenuItemElementCopyToText {
            get {
                return ResourceManager.GetString("MenuItemElementCopyToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete &amp;element.
        /// </summary>
        internal static string MenuItemElementDeleteText {
            get {
                return ResourceManager.GetString("MenuItemElementDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save all element images.
        /// </summary>
        internal static string MenuItemElementSaveAllPicturesText {
            get {
                return ResourceManager.GetString("MenuItemElementSaveAllPicturesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use only Garmin colors for POIs.
        /// </summary>
        internal static string MenuItemExtraGarminColorText {
            get {
                return ResourceManager.GetString("MenuItemExtraGarminColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayed language.
        /// </summary>
        internal static string MenuItemExtraLanguageText {
            get {
                return ResourceManager.GetString("MenuItemExtraLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently opened files.
        /// </summary>
        internal static string MenuItemLastFilesText {
            get {
                return ResourceManager.GetString("MenuItemLastFilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Set color.
        /// </summary>
        internal static string MenuItemLineColor1Text {
            get {
                return ResourceManager.GetString("MenuItemLineColor1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Set color 2.
        /// </summary>
        internal static string MenuItemLineColor2Text {
            get {
                return ResourceManager.GetString("MenuItemLineColor2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy image.
        /// </summary>
        internal static string MenuItemLineCopyText {
            get {
                return ResourceManager.GetString("MenuItemLineCopyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string MenuItemListText {
            get {
                return ResourceManager.GetString("MenuItemListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add new element.
        /// </summary>
        internal static string MenuItemNewElementText {
            get {
                return ResourceManager.GetString("MenuItemNewElementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New.
        /// </summary>
        internal static string MenuItemNewText {
            get {
                return ResourceManager.GetString("MenuItemNewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open.
        /// </summary>
        internal static string MenuItemOpenText {
            get {
                return ResourceManager.GetString("MenuItemOpenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy image.
        /// </summary>
        internal static string MenuItemPointCopyText {
            get {
                return ResourceManager.GetString("MenuItemPointCopyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert image.
        /// </summary>
        internal static string MenuItemPointInsertText {
            get {
                return ResourceManager.GetString("MenuItemPointInsertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open image.
        /// </summary>
        internal static string MenuItemPointLoadText {
            get {
                return ResourceManager.GetString("MenuItemPointLoadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set color to transparent by clicking.
        /// </summary>
        internal static string MenuItemPointSetTranspText {
            get {
                return ResourceManager.GetString("MenuItemPointSetTranspText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string MenuItemSaveText {
            get {
                return ResourceManager.GetString("MenuItemSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile.
        /// </summary>
        internal static string MenuItemTileText {
            get {
                return ResourceManager.GetString("MenuItemTileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF files (*.gif)|*.gif|PNG files (*.png)|*.png|BMP files (*.bmp)|*.bmp|JPG files (*.jpg)|*.jpg|All files|*.*.
        /// </summary>
        internal static string OpenPictureFileDialogFilterText {
            get {
                return ResourceManager.GetString("OpenPictureFileDialogFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open TYP file.
        /// </summary>
        internal static string OpenPictureFileDialogText {
            get {
                return ResourceManager.GetString("OpenPictureFileDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small image.
        /// </summary>
        internal static string SmallImageMenuItemText {
            get {
                return ResourceManager.GetString("SmallImageMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Areas.
        /// </summary>
        internal static string TabPageAreaText {
            get {
                return ResourceManager.GetString("TabPageAreaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linien.
        /// </summary>
        internal static string TabPageLineText {
            get {
                return ResourceManager.GetString("TabPageLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string TabPagePointText {
            get {
                return ResourceManager.GetString("TabPagePointText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FamilyID is unique for a specific card (1..65535).
        /// </summary>
        internal static string TextBoxFamilyIDTooltipText {
            get {
                return ResourceManager.GetString("TextBoxFamilyIDTooltipText", resourceCulture);
            }
        }
    }
}
